// homework-vue/src/views/City/Details.vue
<template>
    <div>
        <h1>Details</h1>
        <h2>City</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">Name</dt>
            <dd class="col-sm-10">
                {{ this.name }}
            </dd>
            <div id="button">
                <button
                    @click="editClicked(entity)"
                    type="button"
                    class="btn btn-primary"
                >
                    Edit
                </button>
            </div>
            <div id="button">
                <button
                    @click="backOnClick()"
                    type="button"
                    class="btn btn-info"
                >
                    Back to List
                </button>
            </div>
        </dl>
    </div>
</template>
<script lang="ts">
import { Vue } from "vue-class-component";
import { ICity } from "../../domain/ICity";
import { Service } from "../../service/Service";
import router from "../../router";

export default class CityDetails extends Vue {
    service: Service<ICity> = new Service<ICity>();

    protected url: string = "https://localhost:5001/api/v1/Cities";

    name: string = "";
    private entity: ICity | null = null;

    async created() {
        this.url = this.url + "/" + this.$route.query.id;
        console.log(this.url);

        const response = await this.service.get(this.url);

        if (response.statusCode >= 200 && response.statusCode < 400) {
            this.name = response.data!.name;
            this.entity = response.data;
        }
    }

    editClicked(city: ICity): void {
        router.push({ name: "CityEdit", query: { id: city.id } });
    }

    backOnClick(): void {
        router.push({ name: "city-index" });
    }

    data() {
        return {
            posts: null,
        };
    }
}
</script>

// react-homework/src/containers/city/Details.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import { ICity } from "../../dto/ICity";
import { useContext, useEffect, useState } from "react";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";
import { useHistory } from "react-router-dom";


const CityDetails = () => {

    //get the router params
    let { id } = useParams() as IRouteId;
    const appState = useContext(AppContext);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [city, setCity] = useState({} as ICity || '');
    let history = useHistory();

    const loadData = async () => {
        console.log(id)

        let result = await BaseService.get<ICity>('/Cities/' + id, appState.token!);


        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setCity(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }

    }

    const editClicked = async (e: Event) => {

        e.preventDefault();
        history.push('/city/Edit/' + id)

    }

    useEffect(() => {
        loadData();
    }, []);
    return (
        <div>
            <h3>Details</h3>
            <h4>City</h4>
            <hr />
            <dl className="row">
                <dt className="col-sm-2">Name</dt>

                <dd className="col-sm-10">
                    {city.name || ''}
                </dd>
                <hr />

                <div className="form-group" >
                <div id="button">
                        <button onClick={(e) => editClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Edit</button>
                        <p id='backToList'>
                        <Link to={'/city'}>Back to List</Link> 
                        </p>
                    </div>

                </div>

            </dl>
        </div>
    );
}

export default CityDetails;
