// react-homework/src/containers/pictures/Index.tsx
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import Loader from "../../components/Loader";
import { IPicture } from "../../dto/IPicture";
import { useContext, useEffect, useState } from "react";
import { data } from "jquery";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";

const RowDisplay = (props: { picture: IPicture }) => (
    <tr>
        <td>
            {props.picture.url}
        </td>
        <td>
            {props.picture.productName}
        </td>
        <td>
            <Link to={'/pictures/' + props.picture.id}>Details</Link> |
            <Link to={'/pictures/edit/' + props.picture.id}>Edit</Link> |
            <Link to={'/pictures/delete/' + props.picture.id}>Delete</Link>
        </td>
    </tr>
);


const PictureIndex = () => {
    const appState = useContext(AppContext);
    const [pictures, setPictures] = useState([] as IPicture[]);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });



    const loadData  = async () => {
       
        console.log(appState)
        let result = await BaseService.getAll<IPicture>('/Pictures', appState.token!);
        console.log(result);
        
        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setPictures(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }

    }
    useEffect(() => {
        loadData();
    }, []);


    return (
        <>
        <h1>Pictures</h1>
        {appState.token != null ?
                <>
                    <p>
                        <Link to={'/pictures/create'}>Create</Link> 
                    </p>

                </>
                :
                <>
                </>
            }
        <table className="table">
            <thead>
                <tr>
                    <th>
                      Url
                    </th>
                    <th>
                      Product Name
                    </th>
                    
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {pictures.map(picture =>
                    <RowDisplay picture={picture} key={picture.id} />)
                }
            </tbody>
        </table>
        <Loader {...pageStatus} />
    </>

    );
}

export default PictureIndex;

// homework-vue/src/views/Pictures/Index.vue
<template>
    <h1>Pictures</h1>
    <p>
        <a class="nav-link text-blue" @click="createClicked()">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Url</th>
                <th>Product Description</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="picture in entity" :key="picture.id">
                <td>{{ picture.url }}</td>
                <td>{{ picture.productName }}</td>
                <div class="col s6 text-right">
                    <td>
                        <button
                            @click="editClicked(picture)"
                            type="button"
                            class="btn btn-primary btn-sm mr-1 btn-right"
                        >
                            Edit
                        </button>
                        <button
                            @click="detailsClicked(picture)"
                            type="button"
                            class="btn btn-info btn-sm mr-1 btn-right"
                        >
                            Details
                        </button>
                        <button
                            @click="deleteClicked(picture)"
                            type="button"
                            class="btn btn-danger btn-sm btn-right"
                        >
                            Delete
                        </button>
                    </td>
                </div>
            </tr>
        </tbody>
    </table>
</template>

<script lang="ts">
import { IPicture } from "../../domain/IPicture";
import { Vue } from "vue-class-component";
import { Service } from "../../service/Service";
import router from "../../router";

export default class Picture extends Vue {
    service: Service<IPicture> = new Service<IPicture>();
    entity: IPicture[] | null = null;
    protected url: string = "https://localhost:5001/api/v1/Pictures";

    async created(): Promise<void> {
        console.log("attached");

        const response = await this.service.getAll(this.url);
        this.entity = response;
    }

    editClicked(picture: IPicture): void {
        this.$router.push({ name: "PictureEdit", query: { id: picture.id } });
    }

    detailsClicked(picture: IPicture): void {
        this.$router.push({
            name: "PictureDetails",
            query: { id: picture.id },
        });
    }

    deleteClicked(picture: IPicture): void {
        this.$router.push({ name: "PictureDelete", query: { id: picture.id } });
    }

    createClicked(): void {
        this.$router.push({ name: "PictureCreate" });
    }
}
</script>
