// homework-vue/src/views/Pictures/Create.vue
<template>
    <h1>Create</h1>
    <h2>Picture</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <div v-if="message" style="color: crimson">{{ message }}</div>

                <label>Url</label>
                <input class="form-control" v-model="pictureUrl" />
            </div>

            <div class="form-group">
                <label>Product</label>
                <select v-model="this.productId" class="form-control">
                    <option value="">--- Please select ---</option>

                    <option
                        v-for="product in products"
                        :key="product.id"
                        v-bind:value="product.id"
                    >
                        {{ product.description }}
                    </option>
                </select>
            </div>
            <div class="row">
                <div id="button">
                    <button
                        @click="saveClicked()"
                        type="button"
                        class="btn btn-primary"
                    >
                        Save
                    </button>
                </div>
                <div id="button">
                    <button
                        @click="backOnClick()"
                        type="button"
                        class="btn btn-info"
                    >
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { Vue } from "vue-class-component";
import { IPicture } from "../../domain/IPicture";
import { IPictureCreate } from "../../domain/IPictureCreate";
import { IProduct } from "../../domain/IProduct";
import { Service } from "../../service/Service";
import router from "../../router";
import store from "@/store/index";

export default class PictureCreate extends Vue {
    service: Service<IPictureCreate> = new Service<IPictureCreate>();
    productService: Service<IProduct> = new Service<IProduct>();
    entity: IPicture | null = null;
    products: IProduct[] | null = null;
    pictureUrl: string = "";
    protected url: string = "https://localhost:5001/api/v1/Pictures";
    protected productUrl: string = "https://localhost:5001/api/v1/Products";
    productId: string = "";
    productName: string = "";
    selectedProduct: any;
    message: string = "";

    async created() {
        const productResponse = await this.productService.getAll(
            this.productUrl
        );
        this.products = productResponse;
        console.log(this.products);
        console.log(store.state.token);
    }

    backOnClick(): void {
        router.push({ name: "picture-index" });
    }

    async saveClicked(): Promise<void> {
        console.log(this.selectedProduct);
        const objToSave: IPictureCreate = {
            url: this.pictureUrl,
            productId: this.selectedProduct.id,
        };
        if (this.url.length < 2) {
            this.message = "Url can't be empty";
            return;
        }
        if (this.selectedProduct.id.length < 2) {
            this.message = "Product can't be empty";
            return;
        }

        console.log(objToSave);
        const response = await this.service.create(objToSave, this.url);

        if (response.statusCode >= 200 && response.statusCode < 400) {
            router.push({ name: "picture-index" });
        }
    }
}
</script>

// react-homework/src/containers/pictures/Create.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import { useContext, useEffect, useState } from "react";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";
import Alert, { EAlertClass } from "../../components/Alert";
import { useHistory } from "react-router-dom";
import { IPicture } from "../../dto/IPicture";
import { IProduct } from "../../dto/IProduct";


const PictureCreate = () => {

    let { id } = useParams() as IRouteId;
    const appState = useContext(AppContext);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [editData, setPicture] = useState({} as IPicture);
    const [alertMessage, setAlertMessage] = useState('');
    const [productData, setProduct] = useState([] as IProduct[]);

    let history = useHistory();
   
   

    const loadData = async () => {
        console.log(id)

        let productResult = await BaseService.getAll<IProduct>('/Products', appState.token!);
        if (productResult.ok && productResult.data) {
            setProduct(productResult.data);
        }
        else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: productResult.statusCode });
        }

    }

    const submitClicked = async (e: Event) => {

        e.preventDefault();
        if(typeof(editData.url) === 'undefined'){
            setAlertMessage('url can not be empty!')
        }

        else if (editData.url.length < 2) {
            setAlertMessage('The field Url must be a string or array type with a minimum length of 2.');
        }
        else if (typeof(editData.productName) === 'undefined') {
            setAlertMessage('Product name can not be empty!');
        } else {
            setAlertMessage('');
            console.log(editData)

            const url = '/Pictures';
            let response = await BaseService.post(url, editData, appState.token!);

            console.log(response)
            if (response.statusCode >= 200 && response.statusCode < 400) {
                history.push('/pictures')
            } else {
                setAlertMessage('Error')
            }
        }
    }


    useEffect(() => {
        loadData();

    }, []);

    return (
        <>
            <h2>Create</h2 >
            <h3>Picture</h3>
            <form onSubmit={(e) => submitClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label>Url</label>
                                <input value={editData.url} onChange={e => setPicture({ ...editData, url: e.target.value })} className="form-control" type="text" id="Input_CityName" name="Input.CityName" autoComplete="current-name" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="formSelect">Product name</label>
                                <select value={editData.productName} onChange={e => setPicture({ ...editData, productId: e.target.value })} className="form-control" id="formSelect">
                                    <option>---Please select---</option>
                                    {productData.map(product =>
                                        <option key={product.id} value={product.id}>{product.description}</option>
                                    )};

                                </select>
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => submitClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Save</button>
                            </div>
                            <p>
                                <Link to={'/pictures'}>Back to List</Link>
                            </p>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default PictureCreate;
