// homework-vue/src/views/Pictures/Delete.vue
<template>
    <div>
        <h1>Delete</h1>
        <h2>Are you sure you want to delete this?</h2>
        <h3>Picture</h3>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">Url</dt>
            <dd class="col-sm-10">
                {{ pictureUrl }}
            </dd>
            <dt class="col-sm-2">Product Name</dt>
            <dd class="col-sm-10">
                {{ productName }}
            </dd>
            <div id="button">
                <button
                    @click="deleteClicked()"
                    type="button"
                    class="btn btn-primary"
                >
                    Delete
                </button>
            </div>
            <div id="button">
                <button
                    @click="backOnClick()"
                    type="button"
                    class="btn btn-info"
                >
                    Back to List
                </button>
            </div>
        </dl>
    </div>
</template>
<script lang="ts">
import { Vue } from "vue-class-component";
import { IPicture } from "../../domain/IPicture";
import { Service } from "../../service/Service";
import router from "../../router";

export default class PictureDelete extends Vue {
    service: Service<IPicture> = new Service<IPicture>();

    protected url: string = "https://localhost:5001/api/v1/Pictures";
    productName: string = "";
    pictureUrl: string = "";
    private entity: IPicture | null = null;

    async created() {
        this.url = this.url + "/" + this.$route.query.id;
        console.log(this.url);

        const response = await this.service.get(this.url);

        if (response.statusCode >= 200 && response.statusCode < 400) {
            this.entity = response.data;
            this.pictureUrl = response.data!.url;
            this.productName = response.data!.productName;
        }

        console.log(this.entity);
    }

    async deleteClicked(): Promise<void> {
        const response = await this.service.delete(this.url);

        if (response.statusCode >= 200 && response.statusCode < 400) {
            router.push({ name: "picture-index" });
        }
    }

    backOnClick(): void {
        router.push({ name: "picture-index" });
    }
}
</script>

// react-homework/src/containers/pictures/Delete.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import { IPicture } from "../../dto/IPicture";
import { useContext, useEffect, useState } from "react";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";
import { useHistory } from "react-router-dom";


const PictureDelete = () => {

    //get the router params
    let { id } = useParams() as IRouteId;
    const appState = useContext(AppContext);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [picture, setPicture] = useState({} as IPicture);
    let history = useHistory();

    const loadData = async () => {
        console.log(id)

        let result = await BaseService.get<IPicture>('/Pictures/' + id, appState.token!);


        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setPicture(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }

    }

    const deleteClicked = async (e: Event) => {

        e.preventDefault();
        let result = await BaseService.delete<IPicture>('/Pictures/' + id, appState.token!);


        if (result.ok ) {
            history.push('/pictures');
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
     

    }

    useEffect(() => {
        loadData();
    }, []);
    return (
        <div>
            <h3>Details</h3>
            <h2>Are you sure you want to delete this?</h2>
            <h3>Picture</h3>
            <hr />
            <dl className="row">
                <dt className="col-sm-2">Url</dt>

                <dd className="col-sm-10">
                    {picture.url}
                </dd>
                <dt className="col-sm-2">Product name</dt>

                <dd className="col-sm-10">
                    {picture.productName}
                </dd>
                <hr />

                <div className="form-group" >
                    <div id="button">
                        <button onClick={(e) => deleteClicked(e.nativeEvent)} type="submit" className="btn btn-danger">Delete</button>
                        <p id="backToList">
                            <Link to={'/pictures'}>Back to List</Link>
                        </p>
                    </div>

                </div>

            </dl>
        </div>
    );
}

export default PictureDelete;
