// homework-vue/src/views/identity/Login.vue
<template>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-6">
            <h4>Use a local account to log in.</h4>
            <div v-if="error" style="color: crimson">{{ error }}</div>
            <div class="form-group">
                <label for="Input_Email">Email</label>
                <input
                    class="form-control"
                    type="email"
                    id="Input_Email"
                    v-model="email"
                />
            </div>
            <div class="form-group">
                <label for="Input_Password">Password</label>
                <input
                    class="form-control"
                    type="password"
                    id="Input_Password"
                    v-model="password"
                />
            </div>
            <div class="form-group">
                <button
                    @click="loginClicked($event)"
                    type="submit"
                    class="btn btn-primary"
                >
                    Log in
                </button>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import router from "../../router";

@Options({
    components: {},
    props: {},
})
export default class Login extends Vue {
    email: string = "";
    password: string = "";
    error: string = "";

    async loginClicked(event: Event): Promise<void> {
        console.log(this.email, this.password, event);
        var regexEmail = /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;

        if (!regexEmail.test(this.email)) {
            this.error = "Email is not valid!";
            return;
        }
        if (this.password.length < 4) {
            this.error = "Password inncorrect!";
            return;
        }

        store.dispatch("logIn", { email: this.email, password: this.password });

        router.push("/");
        if (store.state.token != null) {
            router.push("/");
        } else {
            this.error = "Email or password inncorrect!";
        }
    }
}
</script>

// react-homework/src/containers/identity/Login.tsx
import React, { useContext, useState } from "react";
import { Redirect } from "react-router";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Login = () => {
    const appState = useContext(AppContext);

    const [loginData, setLoginData] = useState({ email: '', password: '' });
    const [alertMessage, setAlertMessage] = useState('');

    const logInClicked = async (e: Event) => {
        e.preventDefault();
       

        setAlertMessage('');
        let response = await IdentityService.Login('Account/Login', loginData);

        console.log(response)
        if (!response.ok) {
          
            setAlertMessage(appState.langResources.common.loginProblem);
        } else {
            setAlertMessage('');


            appState.setAuthInfo(response.data!.token, response.data!.firstname, response.data!.lastname);
        }
        
    }

    return (
        <>
            { appState.token !== null ? <Redirect to="/" /> : null}
            <h1>{appState.langResources.account.logIn}</h1>
            <form onSubmit={(e) => logInClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-4">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_Email">{appState.langResources.account.email}</label>
                                <input value={loginData.email} onChange={e => setLoginData({ ...loginData, email: e.target.value })} className="form-control" type="email" id="Input_Email" name="Input.Email"  autoComplete="username" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Password">{appState.langResources.account.password}</label>
                                <input value={loginData.password} onChange={e => setLoginData({ ...loginData, password: e.target.value })} className="form-control" type="password" id="Input_Password" name="Input.Password"  autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => logInClicked(e.nativeEvent)} type="submit" className="btn btn-primary">{appState.langResources.account.logIn}</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default Login;
