// homework-vue/src/views/identity/Register.vue
<template>
    <div>
        <div class="row">
            <div class="col-md-4">
                <h1>Register</h1>
                <h4>Create a new account.</h4>
                <hr />
                <div v-if="message" style="color: crimson">{{ message }}</div>

                <div
                    class="text-danger validation-summary-valid"
                    data-valmsg-summary="true"
                >
                    <ul>
                        <li style="display: none"></li>
                    </ul>
                </div>
                <div class="form-group">
                    <label for="Input_Firstname">First name</label>
                    <input
                        class="form-control"
                        type="text"
                        data-val="true"
                        data-val-length="The field First name must be a string with a minimum length of 1 and a maximum length of 128."
                        data-val-length-max="128"
                        data-val-length-min="1"
                        data-val-required="The First name field is required."
                        id="Input_Firstname"
                        maxlength="128"
                        v-model="firstname"
                    />
                    <span
                        class="text-danger field-validation-valid"
                        data-valmsg-for="Input.Firstname"
                        data-valmsg-replace="true"
                    ></span>
                </div>
                <div class="form-group">
                    <label for="Input_Lastname">Last name</label>
                    <input
                        class="form-control"
                        type="text"
                        data-val="true"
                        data-val-length="The field Last name must be a string with a minimum length of 1 and a maximum length of 128."
                        data-val-length-max="128"
                        data-val-length-min="1"
                        data-val-required="The Last name field is required."
                        id="Input_Lastname"
                        maxlength="128"
                        v-model="lastname"
                    />
                    <span
                        class="text-danger field-validation-valid"
                        data-valmsg-for="Input.Lastname"
                        data-valmsg-replace="true"
                    ></span>
                </div>
                <div class="form-group">
                    <label for="Input_Email">Email</label>
                    <input
                        class="form-control"
                        type="email"
                        data-val="true"
                        data-val-email="The Email field is not a valid e-mail address."
                        data-val-required="The Email field is required."
                        id="Input_Email"
                        v-model="email"
                    />
                    <span
                        class="text-danger field-validation-valid"
                        data-valmsg-for="Input.Email"
                        data-valmsg-replace="true"
                    ></span>
                </div>
                <div class="form-group">
                    <label for="Input_Password">Password</label>
                    <input
                        class="form-control"
                        type="password"
                        data-val="true"
                        data-val-length="The Password must be at least 6 and at max 100 characters long."
                        data-val-length-max="100"
                        data-val-length-min="6"
                        data-val-required="The Password field is required."
                        id="Input_Password"
                        maxlength="100"
                        v-model="password"
                    />
                    <span
                        class="text-danger field-validation-valid"
                        data-valmsg-for="Input.Password"
                        data-valmsg-replace="true"
                    ></span>
                </div>
                <div class="form-group">
                    <label for="Input_ConfirmPassword">Confirm password</label>
                    <input
                        class="form-control"
                        type="password"
                        data-val="true"
                        data-val-equalto="The password and confirmation password do not match."
                        data-val-equalto-other="*.Password"
                        data-val-required="The Confirm password field is required."
                        id="Input_ConfirmPassword"
                        v-model="password"
                    />
                    <span
                        class="text-danger field-validation-valid"
                        data-valmsg-for="Input.ConfirmPassword"
                        data-valmsg-replace="true"
                    ></span>
                </div>
                <button
                    @click="registerClicked($event)"
                    type="submit"
                    class="btn btn-primary"
                >
                    Register
                </button>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "../../store/index";
import router from "../../router";

@Options({
    components: {},
    props: {},
})
export default class Register extends Vue {
    email: string = "";
    password: string = "";
    firstname: string = "";
    lastname: string = "";
    message: string = "";

  

    async registerClicked(): Promise<void> {
        console.log(this.email, this.password, this.firstname, this.lastname);

        var regexEmail = /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;
        if (this.firstname.length < 1) {
            this.message = "First name can't be empty!";
            return;
        }
        
        if (this.lastname.length < 1) {
            this.message = "Last name can't be empty!";
            return;
        }
        if (!regexEmail.test(this.email)) {
            this.message = "Email is not valid!";
            return;
        }

        console.log(this.password)
        store.dispatch("register", {
            email: this.email,
            password: this.password,
            firstname: this.firstname,
            lastname: this.lastname,
        });

        router.push("/");
        if (store.state.token != null) {
            router.push("/");
        } else {
            this.message = "Email already in use!";
        }
    }
}
</script>

// react-homework/src/containers/identity/Register.tsx
import React, { useContext, useState } from "react";
import { Redirect } from "react-router";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Register = () => {
    const appState = useContext(AppContext);

    const [registerData, setRegisterData] = useState({ email: '', password: '', firstName: '', lastName: '' });
    const [alertMessage, setAlertMessage] = useState('');
    const [confirm, setConfirm] = useState({confirmPassword: ''});

    const regexEmail = /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;


    const registerClicked = async (e: Event) => {
        e.preventDefault();


        if (registerData.email === '' || !regexEmail.test(registerData.email)) {
            setAlertMessage('Email not valid!');
        }
        else if (registerData.firstName === '' || registerData.lastName === '') {
            setAlertMessage('First name or Last name can not be empty');
        } else if (registerData.password !== confirm.confirmPassword){
            setAlertMessage('Passwords do not match!');
        }else {
            let response = await IdentityService.register('account/register', registerData);
            if (!response.ok) {
                setAlertMessage(response.messages![0]);
            } else {
                setAlertMessage('');


                appState.setAuthInfo(response.data!.token, response.data!.firstname, response.data!.lastname);
            }
        }
    }

    return (
        <>
            { appState.token !== null ? <Redirect to="/" /> : null}
            <h1>Register</h1>
            <form onSubmit={(e) => registerClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_FirstName">First name</label>
                                <input value={registerData.firstName} onChange={e => setRegisterData({ ...registerData, firstName: e.target.value })} className="form-control" type="text" id="Input_FirstName" name="Input.FirstName" placeholder="First name..." autoComplete="current-firstName" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_LastName">Last name</label>
                                <input value={registerData.lastName} onChange={e => setRegisterData({ ...registerData, lastName: e.target.value })} className="form-control" type="text" id="Input_LastName" name="Input.LastName" placeholder="Last name..." autoComplete="current-lastName" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Email">Email</label>
                                <input value={registerData.email} onChange={e => setRegisterData({ ...registerData, email: e.target.value })} className="form-control" type="email" id="Input_Email" name="Input.Email" placeholder="user@example.com" autoComplete="username" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Password">Password</label>
                                <input value={registerData.password} onChange={e => setRegisterData({ ...registerData, password: e.target.value })} className="form-control" type="password" id="Input_Password" name="Input.Password" placeholder="Insert your password..." autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_ConfirmPassword">Confirm Password</label>
                                <input value={confirm.confirmPassword} onChange={e => setConfirm({ ...registerData, confirmPassword: e.target.value })} className="form-control" type="password" id="Input_ConfirmPassword" name="Input.ConfirmPassword" placeholder="Confirm your password..." autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => registerClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Register</button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default Register;
