// react-homework/src/containers/city/Create.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import { ICity } from "../../dto/ICity";
import { useContext, useEffect, useState } from "react";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";
import Alert, { EAlertClass } from "../../components/Alert";
import { useHistory } from "react-router-dom";


const CityCreate = () => {

    let { id } = useParams() as IRouteId;
    const appState = useContext(AppContext);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [editData, setCity] = useState({ name: ''});
    const [alertMessage, setAlertMessage] = useState('');
    let history = useHistory();



    const submitClicked = async (e: Event) => {

        e.preventDefault();

        if (editData.name.length < 2 || editData.name.length > 128) {
            setAlertMessage('The field Name must be a string or array type with a minimum length of 2.');

        } else {
            setAlertMessage('');
            console.log(editData)

            const url = '/Cities';
            let response = await BaseService.post(url, editData, appState.token!);

            console.log(response)
            if (response.statusCode >= 200 && response.statusCode < 400) {
                history.push('/city')
            } else {
                setAlertMessage(response.messages![0]);
            }
        }
    }


    useEffect(() => {

    }, []);


    return (
        <>
            <h2>Create</h2 >
            <h3>City</h3>
            <form onSubmit={(e) => submitClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label>Name</label>
                                <input value={editData.name} onChange={e => setCity({ ...editData, name: e.target.value })} className="form-control" type="text" id="Input_CityName" name="Input.CityName" placeholder={editData.name} autoComplete="current-name" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => submitClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Save</button>
                            </div>
                            <p>
                                <Link to={'/city'}>Back to List</Link>
                            </p>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
}

export default CityCreate;

// homework-vue/src/views/City/Create.vue
<template>
    <h1>Create</h1>
    <h2>City</h2>
    <hr />
    <div v-if="message" style="color: crimson">{{ message }}</div>
    <div v-if="error" style="color: crimson">{{ error }}</div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" v-model="name" />
            </div>
            <div class="row">
                <div id="button">
                    <button
                        @click="saveClicked()"
                        type="button"
                        class="btn btn-primary"
                    >
                        Save
                    </button>
                </div>
                <div id="button">
                    <button
                        @click="backOnClick()"
                        type="button"
                        class="btn btn-info"
                    >
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { Vue } from "vue-class-component";
import { ICity } from "../../domain/ICity";
import { Service } from "../../service/Service";
import router from "../../router";

export default class CityCreate extends Vue {
    service: Service<ICity> = new Service<ICity>();
    name: string = "";
    protected url: string = "https://localhost:5001/api/v1/Cities";
    message: string = "";
    error: any;

    async saveClicked() {
        const objToSave: ICity = {
            name: this.name,
        };
        if (this.name.length < 2) {
            this.message = "Minimum name length is 2!";
            return;
        }
        if (this.name.length > 128) {
            this.message = "Maximum name length is 128!";
            return;
        }

        if (this.name.length > 2 && this.message.length < 129) {
            const response = await this.service.create(objToSave, this.url);

            if (response.statusCode >= 200 && response.statusCode < 400) {
                router.push({ name: "city-index" });
            } else {
                this.error = response.errorMessage;
            }
        }
    }

    backOnClick(): void {
        router.push({ name: "city-index" });
    }

    data() {
        return {
            posts: null,
        };
    }
}
</script>
