// react-homework/src/containers/county/Details.tsx
import { useParams } from "react-router-dom";
import { IRouteId } from "../../types/IRouteId";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { Link } from "react-router-dom";
import { ICounty } from "../../dto/ICounty";
import { useContext, useEffect, useState } from "react";
import { AppContext, IAppState, initialAppState } from "../../context/AppContext";
import { useHistory } from "react-router-dom";


const CountyDetails = () => {

    //get the router params
    let { id } = useParams() as IRouteId;
    const appState = useContext(AppContext);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [county, setCounty] = useState({} as ICounty);
    let history = useHistory();

    const loadData = async () => {
        console.log(id)

        let result = await BaseService.get<ICounty>('/Counties/' + id, appState.token!);


        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setCounty(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }

    }

    const editClicked = async (e: Event) => {

        e.preventDefault();
        history.push('/county/Edit/' + id)

    }

    const backClicked = async (e: Event) => {

        e.preventDefault();
        history.push('/county')

    }

    useEffect(() => {
        loadData();
    }, []);
    return (
        <div>
            <h3>Details</h3>
            <h4>County</h4>
            <hr />
            <dl className="row">
                <dt className="col-sm-2">Name</dt>

                <dd className="col-sm-10">
                    {county.name}
                </dd>
                <hr />

                <div className="form-group" >
                    <div id="button">
                        <button onClick={(e) => editClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Edit</button>
                        <p id='backToList'>
                        <Link to={'/county'}>Back to List</Link> 
                        </p>
                    </div>

                </div>

            </dl>
        </div>
    );
}

export default CountyDetails;

// homework-vue/src/views/County/Details.vue
<template>
    <div>
        <h4>County Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">Name</dt>
            <dd class="col-sm-10">
                {{ this.name }}
            </dd>
            <div id="button">
                <button
                    @click="editClicked(entity)"
                    type="button"
                    class="btn btn-primary"
                >
                    Edit
                </button>
            </div>
            <div id="button">
                <button
                    @click="backOnClick()"
                    type="button"
                    class="btn btn-info"
                >
                    Back to List
                </button>
            </div>
        </dl>
    </div>
</template>
<script lang="ts">
import { Vue } from "vue-class-component";
import { ICounty } from "../../domain/ICounty";
import { Service } from "../../service/Service";
import router from "../../router";

export default class CountyDetails extends Vue {
    service: Service<ICounty> = new Service<ICounty>();

    protected url: string = "https://localhost:5001/api/v1/Counties";

    private entity: ICounty | null = null;
    name: string = "";

    async created() {
        this.url = this.url + "/" + this.$route.query.id;
        console.log(this.url);

        const response = await this.service.get(this.url);

        if (response.statusCode >= 200 && response.statusCode < 400) {
            this.name = response.data!.name;
            this.entity = response.data;
        }

        console.log(this.entity);
    }

    editClicked(county: ICounty): void {
        router.push({ name: "CountyEdit", query: { id: county.id } });
    }

    backOnClick(): void {
        router.push({ name: "county-index" });
    }
}
</script>
